import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import type { AccountIdentityService, AuthenticatedAccount } from '../identity/account-identity.js';
import type { DurableSubmissionRequest, DurableSubmissionService } from './durable-submission-service.js';

function sessionCookie(request:FastifyRequest){for(const part of(request.headers.cookie??'').split(';')){const [key,...rest]=part.trim().split('=');if(key==='od_session')return decodeURIComponent(rest.join('='));}return '';}
async function auth(identity:AccountIdentityService,request:FastifyRequest,reply:FastifyReply,write:boolean):Promise<AuthenticatedAccount|null>{try{const token=sessionCookie(request);const session=await identity.authenticate(token);if(!session){void reply.code(401).send({error:{code:'authentication-required'}});return null;}return write?await identity.authenticateWithCsrf(token,typeof request.headers['x-csrf-token']==='string'?request.headers['x-csrf-token']:''):session;}catch{void reply.code(403).send({error:{code:'invalid-session-or-csrf'}});return null;}}
function input(accountId:string,value:unknown):DurableSubmissionRequest{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Invalid durable submission request');const body=value as Record<string,unknown>;if(Object.keys(body).some((key)=>!['problemVersionId','language','sourceCode','idempotencyKey'].includes(key)))throw new Error('Invalid durable submission request');return{learnerId:accountId,problemVersionId:String(body.problemVersionId??''),language:body.language as DurableSubmissionRequest['language'],sourceCode:typeof body.sourceCode==='string'?body.sourceCode:'',idempotencyKey:String(body.idempotencyKey??'')};}
function failure(reply:FastifyReply,error:unknown){const message=error instanceof Error?error.message:'Submission service unavailable';if(message==='Submission idempotency conflict')return reply.code(409).send({error:{code:'idempotency-conflict',message:'This idempotency key was already used for a different submission.'}});if(/^(Invalid|Unknown|Unsupported)/.test(message))return reply.code(400).send({error:{code:'invalid-request',message}});return reply.code(503).send({error:{code:'submission-service-unavailable'}});}

export function registerDurableSubmissionRoutes(app:FastifyInstance,service:DurableSubmissionService,identity:AccountIdentityService){
  app.post('/api/v1/submissions',async(request,reply)=>{try{const account=await auth(identity,request,reply,true);if(!account)return;const result=await service.submit(input(account.userId,request.body));return reply.code(202).header('location',`/api/v1/submissions/${result.id}`).send(result);}catch(error){return failure(reply,error);}});
  app.get<{Params:{id:string}}>('/api/v1/submissions/:id',async(request,reply)=>{try{const account=await auth(identity,request,reply,false);if(!account)return;return await service.get(request.params.id,account.userId)??reply.code(404).send({error:{code:'submission-not-found'}});}catch(error){return failure(reply,error);}});
  app.delete<{Params:{id:string}}>('/api/v1/submissions/:id',async(request,reply)=>{try{const account=await auth(identity,request,reply,true);if(!account)return;return await service.cancel(request.params.id,account.userId)??reply.code(404).send({error:{code:'submission-not-found'}});}catch(error){return failure(reply,error);}});
  app.get('/api/v1/operations/judging/metrics',async(request,reply)=>{try{const account=await auth(identity,request,reply,false);if(!account)return;if(!account.roles.includes('admin'))return reply.code(403).send({error:{code:'admin-role-required'}});return await service.metrics();}catch(error){return failure(reply,error);}});
  app.get('/api/v1/judge-packs/available',async(request,reply)=>{try{if(!await auth(identity,request,reply,false))return;return{packs:await service.availablePacks()};}catch(error){return failure(reply,error);}});
}
